/*
 * gsttiimgdec.c
 *
 * This file defines the "TIImgdec" element, which decodes a JPEG image using
 * the xDM 0.9 interface.
 *
 * Example usage:
 *     gst-launch filesrc location=<input file> ! TIImgdec ! filesink location=<output file>
 *
 * Original Author:
 *     Chase Maupin, Texas Instruments, Inc.
 *
 * Copyright (C) $year Texas Instruments Incorporated - http://www.ti.com/
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation version 2.1 of the License.
 *
 * This program is distributed #as is# WITHOUT ANY WARRANTY of any kind,
 * whether express or implied; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <stdio.h>
#include <string.h>
#include <gst/gst.h>
#include <gst/video/video.h>
#include <ctype.h>

#include <ti/sdo/dmai/Dmai.h>
#include <ti/sdo/dmai/Cpu.h>
#include <ti/sdo/dmai/Buffer.h>
#include <ti/sdo/dmai/BufferGfx.h>
#include <ti/sdo/dmai/BufTab.h>
#include <ti/sdo/dmai/ce/Idec.h>

#include "gsttiimgdec.h"
#include "gsttidmaibuffertransport.h"
#include "gstticodecs.h"
#include "gsttithreadprops.h"
#include "gstticommonutils.h"

/* Declare variable used to categorize GST_LOG output */
GST_DEBUG_CATEGORY_STATIC (gst_tiimgdec_debug);
#define GST_CAT_DEFAULT gst_tiimgdec_debug

/* Element property identifiers */
enum
{
  PROP_0,
  PROP_ENGINE_NAME,     /* engineName     (string)  */
  PROP_CODEC_NAME,      /* codecName      (string)  */
  PROP_NUM_OUTPUT_BUFS, /* numOutputBufs  (int)     */
  PROP_FRAMERATE,       /* frameRate      (int)     */
  PROP_RESOLUTION,      /* resolution     (string)  */
  PROP_DISPLAY_BUFFER,  /* displayBuffer  (boolean) */
  PROP_GEN_TIMESTAMPS   /* genTimeStamps  (boolean) */
};

/* Define sink (input) pad capabilities */
static GstStaticPadTemplate sink_factory = GST_STATIC_PAD_TEMPLATE(
    "sink",
    GST_PAD_SINK,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS
    ("video/x-jpeg, "
        "width=(int)[ 1, MAX ], "
        "height=(int)[ 1, MAX ], "
        "framerate=(fraction)[ 0, MAX ]"
    )
);

/* Define source (output) pad capabilities */
static GstStaticPadTemplate src_factory = GST_STATIC_PAD_TEMPLATE(
    "src",
    GST_PAD_SRC,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS
    ("video/x-raw-yuv, "                        /* UYVY */
         "format=(fourcc)UYVY, "
         "framerate=(fraction)[ 0, MAX ], "
         "width=(int)[ 1, MAX ], "
         "height=(int)[ 1, MAX ]"
    )
);

/* Constants */
#define gst_tiimgdec_CODEC_FREE 0x2

/* Declare a global pointer to our element base class */
static GstElementClass *parent_class = NULL;

/* Static Function Declarations */
static void
 gst_tiimgdec_base_init(gpointer g_class);
static void
 gst_tiimgdec_class_init(GstTIImgdecClass *g_class);
static void
 gst_tiimgdec_init(GstTIImgdec *object, GstTIImgdecClass *g_class);
static void
 gst_tiimgdec_set_property (GObject *object, guint prop_id,
     const GValue *value, GParamSpec *pspec);
static void
 gst_tiimgdec_get_property (GObject *object, guint prop_id, GValue *value,
     GParamSpec *pspec);
static gboolean
 gst_tiimgdec_set_sink_caps(GstPad *pad, GstCaps *caps);
static gboolean
 gst_tiimgdec_set_source_caps(GstTIImgdec *imgdec, Buffer_Handle hBuf);
static gboolean
 gst_tiimgdec_sink_event(GstPad *pad, GstEvent *event);
static GstFlowReturn
 gst_tiimgdec_chain(GstPad *pad, GstBuffer *buf);
static gboolean
 gst_tiimgdec_init_image(GstTIImgdec *imgdec);
static gboolean
 gst_tiimgdec_exit_image(GstTIImgdec *imgdec);
static GstStateChangeReturn
 gst_tiimgdec_change_state(GstElement *element, GstStateChange transition);
static void*
 gst_tiimgdec_decode_thread(void *arg);
static void*
 gst_tiimgdec_queue_thread(void *arg);
static void
 gst_tiimgdec_broadcast_queue_thread(GstTIImgdec *imgdec);
static void
 gst_tiimgdec_wait_on_queue_thread(GstTIImgdec *imgdec,
     Int32 waitQueueSize);
static void
 gst_tiimgdec_drain_pipeline(GstTIImgdec *imgdec);
static GstClockTime
 gst_tiimgdec_frame_duration(GstTIImgdec *imgdec);
static char *
 gst_tiimgdec_codec_color_space_to_str(int cspace);
static int 
 gst_tiimgdec_codec_color_space_to_fourcc(int cspace);
static gboolean 
    gst_tiimgdec_codec_start (GstTIImgdec  *imgdec);
static gboolean 
    gst_tiimgdec_codec_stop (GstTIImgdec  *imgdec);
static void 
    gst_tiimgdec_init_env(GstTIImgdec *imgdec);

/******************************************************************************
 * gst_tiimgdec_class_init_trampoline
 *    Boiler-plate function auto-generated by "make_element" script.
 ******************************************************************************/
static void gst_tiimgdec_class_init_trampoline(gpointer g_class,
                gpointer data)
{
    GST_LOG("Begin\n");
    parent_class = (GstElementClass*) g_type_class_peek_parent(g_class);
    gst_tiimgdec_class_init((GstTIImgdecClass*)g_class);
    GST_LOG("Finish\n");
}


/******************************************************************************
 * gst_tiimgdec_get_type
 *    Boiler-plate function auto-generated by "make_element" script.
 *    Defines function pointers for initialization routines for this element.
 ******************************************************************************/
GType gst_tiimgdec_get_type(void)
{
    static GType object_type = 0;

    GST_LOG("Begin\n");
    if (G_UNLIKELY(object_type == 0)) {
        static const GTypeInfo object_info = {
            sizeof(GstTIImgdecClass),
            gst_tiimgdec_base_init,
            NULL,
            gst_tiimgdec_class_init_trampoline,
            NULL,
            NULL,
            sizeof(GstTIImgdec),
            0,
            (GInstanceInitFunc) gst_tiimgdec_init
        };

        object_type = g_type_register_static((gst_element_get_type()),
                          "GstTIImgdec", &object_info, (GTypeFlags)0);

        /* Initialize GST_LOG for this object */
        GST_DEBUG_CATEGORY_INIT(gst_tiimgdec_debug, "TIImgdec", 0,
            "TI xDM 0.9 Image Decoder");

        GST_LOG("initialized get_type\n");

    }

    GST_LOG("Finish\n");
    return object_type;
};


/******************************************************************************
 * gst_tiimgdec_base_init
 *    Boiler-plate function auto-generated by "make_element" script.
 *    Initializes element base class.
 ******************************************************************************/
static void gst_tiimgdec_base_init(gpointer gclass)
{
    static GstElementDetails element_details = {
        "TI xDM 0.9 Image Decoder",
        "Codec/Decoder/Image",
        "Decodes a JPEG using an xDM 0.9-based codec",
        "Chase Maupin; Texas Instruments, Inc."
    };
    GST_LOG("Begin\n");

    GstElementClass *element_class = GST_ELEMENT_CLASS(gclass);

    gst_element_class_add_pad_template(element_class,
        gst_static_pad_template_get (&src_factory));
    gst_element_class_add_pad_template(element_class,
        gst_static_pad_template_get (&sink_factory));
    gst_element_class_set_details(element_class, &element_details);
    GST_LOG("Finish\n");
}


/******************************************************************************
 * gst_tiimgdec_class_init
 *    Boiler-plate function auto-generated by "make_element" script.
 *    Initializes the TIImgdec class.
 ******************************************************************************/
static void gst_tiimgdec_class_init(GstTIImgdecClass *klass)
{
    GObjectClass    *gobject_class;
    GstElementClass *gstelement_class;

    gobject_class    = (GObjectClass*)    klass;
    gstelement_class = (GstElementClass*) klass;

    GST_LOG("Begin\n");

    gobject_class->set_property = gst_tiimgdec_set_property;
    gobject_class->get_property = gst_tiimgdec_get_property;

    gstelement_class->change_state = gst_tiimgdec_change_state;

    g_object_class_install_property(gobject_class, PROP_ENGINE_NAME,
        g_param_spec_string("engineName", "Engine Name",
            "Engine name used by Codec Engine", "unspecified",
            G_PARAM_READWRITE));

    g_object_class_install_property(gobject_class, PROP_CODEC_NAME,
        g_param_spec_string("codecName", "Codec Name", "Name of image codec",
            "unspecified", G_PARAM_READWRITE));

    g_object_class_install_property(gobject_class, PROP_RESOLUTION,
        g_param_spec_string("resolution", "Image Resolution",
            "The resolution of the input image ('width'x'height')\n",
            "720x480", G_PARAM_WRITABLE));

    /* We allow more that one output buffer because this is the buffer that
     * is sent to the downstream element.  It may be that we need to have
     * more than 1 buffer for the mjpeg case if the downstream element
     * doesn't give the buffer back in time for the codec to use.
     */
    g_object_class_install_property(gobject_class, PROP_NUM_OUTPUT_BUFS,
        g_param_spec_int("numOutputBufs",
            "Number of Ouput Buffers",
            "Number of output buffers to allocate for codec",
            1, G_MAXINT32, 1, G_PARAM_WRITABLE));

    /* For MJPEG we will communicate a frame rate to the down stream
     * element.  This can be ignored normally.
     */
    g_object_class_install_property(gobject_class, PROP_FRAMERATE,
        g_param_spec_int("frameRate",
            "Frame rate to play output",
            "Communicate this framerate to downstream elements.  The frame "
            "rate specified should be an integer.  If 29.97fps is desired, "
            "specify 30 for this setting",
            1, G_MAXINT32, 30, G_PARAM_WRITABLE));

    g_object_class_install_property(gobject_class, PROP_DISPLAY_BUFFER,
        g_param_spec_boolean("displayBuffer", "Display Buffer",
            "Display circular buffer status while processing",
            FALSE, G_PARAM_WRITABLE));

    g_object_class_install_property(gobject_class, PROP_GEN_TIMESTAMPS,
        g_param_spec_boolean("genTimeStamps", "Generate Time Stamps",
            "Set timestamps on output buffers",
            TRUE, G_PARAM_WRITABLE));

    GST_LOG("Finish\n");
}

/******************************************************************************
 * gst_tiimgdec_init_env
 *  Initialize element property default by reading environment variables.
 *****************************************************************************/
static void gst_tiimgdec_init_env(GstTIImgdec *imgdec)
{
    GST_LOG("gst_tiimgdec_init_env - begin");

    if (gst_ti_env_is_defined("GST_TI_TIImgdec_engineName")) {
        imgdec->engineName = gst_ti_env_get_string("GST_TI_TIImgdec_engineName");
        GST_LOG("Setting engineName=%s\n", imgdec->engineName);
    }

    if (gst_ti_env_is_defined("GST_TI_TIImgdec_codecName")) {
        imgdec->codecName = gst_ti_env_get_string("GST_TI_TIImgdec_codecName");
        GST_LOG("Setting codecName=%s\n", imgdec->codecName);
    }
    
    if (gst_ti_env_is_defined("GST_TI_TIImgdec_numOutputBufs")) {
        imgdec->numOutputBufs = 
                            gst_ti_env_get_int("GST_TI_TIImgdec_numOutputBufs");
        GST_LOG("Setting numOutputBufs=%ld\n", imgdec->numOutputBufs);
    }
    
    if (gst_ti_env_is_defined("GST_TI_TIImgdec_displayBuffer")) {
        imgdec->displayBuffer = 
                gst_ti_env_get_boolean("GST_TI_TIImgdec_displayBuffer");
        GST_LOG("Setting displayBuffer=%s\n",
                 imgdec->displayBuffer  ? "TRUE" : "FALSE");
    }

   if (gst_ti_env_is_defined("GST_TI_TIImgdec_genTimeStamps")) {
        imgdec->genTimeStamps = 
                gst_ti_env_get_boolean("GST_TI_TIImgdec_genTimeStamps");
        GST_LOG("Setting genTimeStamps =%s\n", 
                    imgdec->genTimeStamps ? "TRUE" : "FALSE");
    }
    
    if (gst_ti_env_is_defined("GST_TI_TIImgdec_framerate")) {
        imgdec->framerateNum = gst_ti_env_get_int("GST_TI_TIImgdec_framerate");
        imgdec->framerateDen = 1;
        
       /* If 30fps was specified, use 29.97 */        
        if (imgdec->framerateNum == 30) {
            imgdec->framerateNum = 30000;
            imgdec->framerateDen = 1001;
        }
    }

    if (gst_ti_env_is_defined("GST_TI_TIImgdec_resolution")) {
        sscanf(gst_ti_env_get_string("GST_TI_TIImgdec_resolution"), "%dx%d", 
                &imgdec->width,&imgdec->height);
        GST_LOG("Setting resolution=%dx%d\n", imgdec->width, imgdec->height);
    }
    
    GST_LOG("gst_tiimgdec_init_env - end");
}

/******************************************************************************
 * gst_tiimgdec_init
 *    Initializes a new element instance, instantiates pads and sets the pad
 *    callback functions.
 ******************************************************************************/
static void gst_tiimgdec_init(GstTIImgdec *imgdec, GstTIImgdecClass *gclass)
{
    GST_LOG("Begin\n");
    /* Instantiate decoded image sink pad
     *
     * Fixate on our static template caps insteam of writing a getcaps
     * function which is overkill for this element.
     */
    imgdec->sinkpad =
        gst_pad_new_from_static_template(&sink_factory, "sink");
    gst_pad_set_setcaps_function(
        imgdec->sinkpad, GST_DEBUG_FUNCPTR(gst_tiimgdec_set_sink_caps));
//    gst_pad_set_getcaps_function(
//        imgdec->sinkpad, GST_DEBUG_FUNCPTR(gst_pad_proxy_getcaps));
    gst_pad_set_event_function(
        imgdec->sinkpad, GST_DEBUG_FUNCPTR(gst_tiimgdec_sink_event));
    gst_pad_set_chain_function(
        imgdec->sinkpad, GST_DEBUG_FUNCPTR(gst_tiimgdec_chain));
    gst_pad_fixate_caps(imgdec->sinkpad,
        gst_caps_make_writable(
            gst_caps_copy(gst_pad_get_pad_template_caps(imgdec->sinkpad))));

    /* Instantiate deceoded image source pad
     *
     * Fixate on our static template caps insteam of writing a getcaps
     * function which is overkill for this element.
     */
    imgdec->srcpad =
        gst_pad_new_from_static_template(&src_factory, "src");
//    gst_pad_set_getcaps_function(
//        imgdec->srcpad, GST_DEBUG_FUNCPTR(gst_pad_proxy_getcaps));
    gst_pad_fixate_caps(imgdec->srcpad,
        gst_caps_make_writable(
            gst_caps_copy(gst_pad_get_pad_template_caps(imgdec->srcpad))));

    /* Add pads to TIImgdec element */
    gst_element_add_pad(GST_ELEMENT(imgdec), imgdec->sinkpad);
    gst_element_add_pad(GST_ELEMENT(imgdec), imgdec->srcpad);

    /* Initialize TIImgdec state */
    imgdec->engineName         = NULL;
    imgdec->codecName          = NULL;
    imgdec->displayBuffer      = FALSE;
    imgdec->genTimeStamps      = FALSE;
    imgdec->width              = 0;
    imgdec->height             = 0;

    imgdec->hEngine            = NULL;
    imgdec->hIe                = NULL;
    imgdec->drainingEOS        = FALSE;
    imgdec->threadStatus       = 0UL;
    imgdec->capsSet            = FALSE;

    imgdec->decodeDrained      = FALSE;
    imgdec->waitOnDecodeDrain  = NULL;
    imgdec->waitOnBufTab       = NULL;

    imgdec->waitOnDecodeThread = NULL;

    imgdec->hInFifo            = NULL;

    imgdec->waitOnQueueThread  = NULL;
    imgdec->waitQueueSize      = 0;

    imgdec->framerateNum       = 0;
    imgdec->framerateDen       = 0;

    imgdec->numOutputBufs      = 0UL;
    imgdec->hOutBufTab         = NULL;
    imgdec->circBuf            = NULL;

    gst_tiimgdec_init_env(imgdec);

    GST_LOG("Finish\n");
}

/******************************************************************************
 * gst_tiimgdec_set_property
 *     Set element properties when requested.
 ******************************************************************************/
static void gst_tiimgdec_set_property(GObject *object, guint prop_id,
                const GValue *value, GParamSpec *pspec)
{
    GstTIImgdec *imgdec = GST_TIIMGDEC(object);

    GST_LOG("Begin\n");

    switch (prop_id) {
        case PROP_ENGINE_NAME:
            if (imgdec->engineName) {
                g_free((gpointer)imgdec->engineName);
            }
            imgdec->engineName =
                (gchar*)g_malloc(strlen(g_value_get_string(value)) + 1);
            strcpy((gchar *)imgdec->engineName, g_value_get_string(value));
            GST_LOG("setting \"engineName\" to \"%s\"\n", imgdec->engineName);
            break;
        case PROP_CODEC_NAME:
            if (imgdec->codecName) {
                g_free((gpointer)imgdec->codecName);
            }
            imgdec->codecName =
                (gchar*)g_malloc(strlen(g_value_get_string(value)) + 1);
            strcpy((gchar*)imgdec->codecName, g_value_get_string(value));
            GST_LOG("setting \"codecName\" to \"%s\"\n", imgdec->codecName);
            break;
        case PROP_RESOLUTION:
            sscanf(g_value_get_string(value), "%dx%d", &imgdec->width,
                    &imgdec->height);
            GST_LOG("setting \"resolution\" to \"%dx%d\"\n",
                imgdec->width, imgdec->height);
            break;
        case PROP_NUM_OUTPUT_BUFS:
            imgdec->numOutputBufs = g_value_get_int(value);
            GST_LOG("setting \"numOutputBufs\" to \"%ld\"\n",
                imgdec->numOutputBufs);
            break;
        case PROP_FRAMERATE:
        {
            imgdec->framerateNum = g_value_get_int(value);
            imgdec->framerateDen = 1;

            /* If 30fps was specified, use 29.97 */
            if (imgdec->framerateNum == 30) {
                imgdec->framerateNum = 30000;
                imgdec->framerateDen = 1001;
            }

            GST_LOG("setting \"frameRate\" to \"%2.2lf\"\n",
                (gdouble)imgdec->framerateNum /
                (gdouble)imgdec->framerateDen);
            break;
        }
        case PROP_DISPLAY_BUFFER:
            imgdec->displayBuffer = g_value_get_boolean(value);
            GST_LOG("setting \"displayBuffer\" to \"%s\"\n",
                imgdec->displayBuffer ? "TRUE" : "FALSE");
            break;
        case PROP_GEN_TIMESTAMPS:
            imgdec->genTimeStamps = g_value_get_boolean(value);
            GST_LOG("setting \"genTimeStamps\" to \"%s\"\n",
                imgdec->genTimeStamps ? "TRUE" : "FALSE");
            break;
        default:
            G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
            break;
    }

    GST_LOG("Finish\n");
}

/******************************************************************************
 * gst_tiimgdec_get_property
 *     Return values for requested element property.
 ******************************************************************************/
static void gst_tiimgdec_get_property(GObject *object, guint prop_id,
                GValue *value, GParamSpec *pspec)
{
    GstTIImgdec *imgdec = GST_TIIMGDEC(object);

    GST_LOG("Begin\n");

    switch (prop_id) {
        case PROP_ENGINE_NAME:
            g_value_set_string(value, imgdec->engineName);
            break;
        case PROP_CODEC_NAME:
            g_value_set_string(value, imgdec->codecName);
            break;
        default:
            G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
            break;
    }

    GST_LOG("Finish\n");
}

/*******************************************************************************
 * gst_tiimgdec_set_sink_caps_helper
 *     This function will look at the capabilities given and set the values
 *     for the decoder if they were not specified on the command line.
 *     It returns TRUE if everything passes and FALSE if there is no
 *     capability in the buffer and the value was not specified on the
 *     command line.
 ******************************************************************************/
static gboolean gst_tiimgdec_set_sink_caps_helper(GstPad *pad, GstCaps *caps)
{
    GstTIImgdec *imgdec;
    GstStructure *capStruct;
    const gchar  *mime;
    GstTICodec   *codec = NULL;

    GST_LOG("Begin\n");

    imgdec   = GST_TIIMGDEC(gst_pad_get_parent(pad));

    /* Set the default values */
    imgdec->params = Idec_Params_DEFAULT;
    imgdec->dynParams = Idec_DynamicParams_DEFAULT;

    /* Set codec to JPEG Decoder */
    codec = gst_ticodec_get_codec("JPEG Image Decoder");

    /* Report if the required codec was not found */
    if (!codec) {
        GST_ERROR("unable to find codec needed for stream");
        return FALSE;
    }

    /* Configure the element to use the detected engine name and codec, unless
     * they have been using the set_property function.
     */
    if (!imgdec->engineName) {
        imgdec->engineName = codec->CE_EngineName;
    }
    if (!imgdec->codecName) {
        imgdec->codecName = codec->CE_CodecName;
    }

    if (!caps) {
        GST_INFO("No caps on input.  Using command line values");
        imgdec->capsSet = TRUE;
        return TRUE;
    }

    capStruct = gst_caps_get_structure(caps, 0);
    mime      = gst_structure_get_name(capStruct);

    GST_INFO("requested sink caps:  %s", gst_caps_to_string(caps));

    /* Generic Video Properties */
    if (!strncmp(mime, "video/", 6)) {
        gint  framerateNum;
        gint  framerateDen;
        gint  width;
        gint  height;
   
        if (!imgdec->framerateNum) {        
            if (gst_structure_get_fraction(capStruct, "framerate", 
                                &framerateNum, &framerateDen)) {
                imgdec->framerateNum = framerateNum;
                imgdec->framerateDen = framerateDen;
            }
        }

        /* Get the width and height of the frame if available */
        if (!imgdec->width)
            if (gst_structure_get_int(capStruct, "width", &width)) 
                imgdec->params.maxWidth = width;
        if (!imgdec->height)
            if (gst_structure_get_int(capStruct, "height", &height))
                imgdec->params.maxHeight = height;
    }

    /* Shut-down any running image decoder */
    if (!gst_tiimgdec_exit_image(imgdec)) {
        GST_ERROR("unable to shut-down running image decoder");
        return FALSE;
    }

    /* Flag that we have run this code at least once */
    imgdec->capsSet = TRUE;

    GST_LOG("Finish\n");
    return TRUE;
}

/******************************************************************************
 * gst_tiimgdec_set_sink_caps
 *     Negotiate our sink pad capabilities.
 ******************************************************************************/
static gboolean gst_tiimgdec_set_sink_caps(GstPad *pad, GstCaps *caps)
{
    GstTIImgdec *imgdec;
    imgdec   = GST_TIIMGDEC(gst_pad_get_parent(pad));

    GST_LOG("Begin\n");

    /* If this call fails then unref the gobject */
    if (!gst_tiimgdec_set_sink_caps_helper(pad, caps)) {
        GST_ERROR("stream type not supported");
        gst_object_unref(imgdec);
        return FALSE;
    }

    GST_LOG("sink caps negotiation successful\n");
    GST_LOG("Finish\n");
    return TRUE;
}


/******************************************************************************
 * gst_tiimgdec_set_source_caps
 *     Negotiate our source pad capabilities.
 ******************************************************************************/
static gboolean gst_tiimgdec_set_source_caps(
                    GstTIImgdec *imgdec, Buffer_Handle hBuf)
{
    BufferGfx_Dimensions  dim;
    GstCaps              *caps;
    gboolean              ret;
    GstPad               *pad;
    guint32              format;

    GST_LOG("Begin\n");
    pad = imgdec->srcpad;

    /* Create a UYVY caps object using the dimensions from the given buffer */
    BufferGfx_getDimensions(hBuf, &dim);

    format = gst_tiimgdec_codec_color_space_to_fourcc(imgdec->params.forceChromaFormat);

    if (format == -1) {
        GST_ERROR("Could not convert codec color space to fourcc");
        return FALSE;
    }
    caps =
        gst_caps_new_simple("video/x-raw-yuv",
            "format",    GST_TYPE_FOURCC,   format,
            "framerate", GST_TYPE_FRACTION, imgdec->framerateNum,
                                            imgdec->framerateDen,
            "width",     G_TYPE_INT,        dim.width,
            "height",    G_TYPE_INT,        dim.height,
            NULL);

    /* Set the source pad caps */
    GST_DEBUG("setting source caps to UYVY:  %s", gst_caps_to_string(caps));
    ret = gst_pad_set_caps(pad, caps);
    gst_caps_unref(caps);

    GST_LOG("Finish\n");
    return ret;
}


/******************************************************************************
 * gst_tiimgdec_sink_event
 *     Perform event processing on the input stream.  At the moment, this
 *     function isn't needed as this element doesn't currently perform any
 *     specialized event processing.  We'll leave it in for now in case we need
 *     it later on.
 ******************************************************************************/
static gboolean gst_tiimgdec_sink_event(GstPad *pad, GstEvent *event)
{
    GstTIImgdec *imgdec;
    gboolean      ret;

    GST_LOG("Begin\n");

    imgdec = GST_TIIMGDEC(GST_OBJECT_PARENT(pad));

    GST_DEBUG("pad \"%s\" received:  %s\n", GST_PAD_NAME(pad),
        GST_EVENT_TYPE_NAME(event));

    switch (GST_EVENT_TYPE(event)) {

        case GST_EVENT_NEWSEGMENT:
            /* maybe save and/or update the current segment (e.g. for output
             * clipping) or convert the event into one in a different format
             * (e.g. BYTES to TIME) or drop it and set a flag to send a
             * newsegment event in a different format later
             */
            ret = gst_pad_push_event(imgdec->srcpad, event);
            break;

        case GST_EVENT_EOS:
            /* end-of-stream: process any remaining decoded frame data */
            GST_LOG("no more input; draining remaining decoded image data\n");

            if (!imgdec->drainingEOS) {
               gst_tiimgdec_drain_pipeline(imgdec);
             }

            /* Propagate EOS to downstream elements */
            ret = gst_pad_push_event(imgdec->srcpad, event);
            break;

        case GST_EVENT_FLUSH_STOP:
            ret = gst_pad_push_event(imgdec->srcpad, event);
            break;

        /* Unhandled events */
        case GST_EVENT_BUFFERSIZE:
        case GST_EVENT_CUSTOM_BOTH:
        case GST_EVENT_CUSTOM_BOTH_OOB:
        case GST_EVENT_CUSTOM_DOWNSTREAM:
        case GST_EVENT_CUSTOM_DOWNSTREAM_OOB:
        case GST_EVENT_CUSTOM_UPSTREAM:
        case GST_EVENT_FLUSH_START:
        case GST_EVENT_NAVIGATION:
        case GST_EVENT_QOS:
        case GST_EVENT_SEEK:
        case GST_EVENT_TAG:
        default:
            ret = gst_pad_event_default(pad, event);
            break;

    }

    GST_LOG("Finish\n");
    return ret;

}


/******************************************************************************
 * gst_tiimgdec_chain
 *    This is the main processing routine.  This function receives a buffer
 *    from the sink pad, processes it, and pushes the result to the source
 *    pad.
 ******************************************************************************/
static GstFlowReturn gst_tiimgdec_chain(GstPad * pad, GstBuffer * buf)
{
    GstTIImgdec *imgdec       = GST_TIIMGDEC(GST_OBJECT_PARENT(pad));
    GstCaps      *caps          = GST_BUFFER_CAPS(buf);
    gboolean     checkResult;

    GST_LOG("Begin\n");
    /* If any thread aborted, communicate it to the pipeline */
    if (gst_tithread_check_status(
            imgdec, TIThread_ANY_ABORTED, checkResult)) {
       gst_buffer_unref(buf);
       return GST_FLOW_UNEXPECTED;
    }

    /* If we have not negotiated the caps at least once then do so now */
    if (!imgdec->capsSet) {
        if (!gst_tiimgdec_set_sink_caps_helper(pad, caps)) {
            GST_ERROR("Could not set caps");
            return GST_FLOW_UNEXPECTED;
        }
    }

    /* If our engine handle is currently NULL, then either this is our first
     * buffer or the upstream element has re-negotiated our capabilities which
     * resulted in our engine being closed.  In either case, we need to
     * initialize (or re-initialize) our image decoder to handle the new
     * stream.
     */
    if (imgdec->hEngine == NULL) {
        if (!gst_tiimgdec_init_image(imgdec)) {
            GST_ERROR("unable to initialize image\n");
            return GST_FLOW_UNEXPECTED;
        }

        GST_TICIRCBUFFER_TIMESTAMP(imgdec->circBuf) =
            GST_CLOCK_TIME_IS_VALID(GST_BUFFER_TIMESTAMP(buf)) ?
            GST_BUFFER_TIMESTAMP(buf) : 0ULL;
    }

    /* Don't queue up too many buffers -- if we collect too many input buffers
     * without consuming them we'll run out of memory.  Once we reach a
     * threshold, block until the queue thread removes some buffers.
     */
    Rendezvous_reset(imgdec->waitOnQueueThread);
    if (Fifo_getNumEntries(imgdec->hInFifo) > 500) {
        gst_tiimgdec_wait_on_queue_thread(imgdec, 400);
    }

    /* Queue up the decoded data stream into a circular buffer */
    if (Fifo_put(imgdec->hInFifo, buf) < 0) {
        GST_ERROR("Failed to send buffer to queue thread\n");
        return GST_FLOW_UNEXPECTED;
    }

    GST_LOG("Finish\n");

    return GST_FLOW_OK;
}

/*******************************************************************************
 * gst_tiimgdec_codec_color_space_to_str
 *      Converts the codec color space values to the corresponding
 *      human readable string value
*******************************************************************************/
static char *gst_tiimgdec_codec_color_space_to_str(int cspace) {
    GST_LOG("Begin");
    switch (cspace) {
        case XDM_YUV_422ILE:
            GST_LOG("Finish");
            return "UYVY";
            break;
        case XDM_YUV_420P:
            GST_LOG("Finish");
            return "YUV420P";
            break;
        case XDM_YUV_422P:
            GST_LOG("Finish");
            return "YUV422P";
            break;
        default:
            GST_ERROR("Unknown xDM color space");
            GST_LOG("Finish");
            return "Unknown";
    }
}

/*******************************************************************************
 * gst_tiimgdec_codec_color_space_to_fourcc
 *      Converts the codec color space values to the corresponding
 *      fourcc values
*******************************************************************************/
static int gst_tiimgdec_codec_color_space_to_fourcc(int cspace) {
    GST_LOG("Begin");
    switch (cspace) {
        case XDM_YUV_422ILE:
            GST_LOG("Finish");
            return GST_MAKE_FOURCC('U', 'Y', 'V', 'Y');
            break;
        case XDM_YUV_420P:
            GST_LOG("Finish");
            return GST_MAKE_FOURCC('I', '4', '2', '0');
            break;
        case XDM_YUV_422P:
            GST_LOG("Finish");
            return GST_MAKE_FOURCC('Y', '4', '2', 'B');
            break;
        default:
            GST_ERROR("Unknown xDM color space");
            GST_LOG("Finish");
            return -1;
            break;
    }
}

/*******************************************************************************
 * gst_tiimgdec_set_codec_attrs
 *     Set the attributes for the decode codec.  The general order is to give
 *     preferdece to values passed in by the user on the command line,
 *     then check the stream for the information.  If the required information
 *     cannot be determined by either method then error out.
 ******************************************************************************/
static gboolean gst_tiimgdec_set_codec_attrs(GstTIImgdec *imgdec)
{ 
    char *toColor;
    GST_LOG("Begin\n");

    /* Set Resolution 
     *
     * NOTE:  We assume that there is only 1 resolution.  i.e. there is
     *        no seperate value being used for input resolution and
     *        output resolution
     */
    imgdec->params.maxWidth = 
                    imgdec->width == 0 ?
                    imgdec->params.maxWidth :
                    imgdec->width;
    imgdec->params.maxHeight =
                    imgdec->height == 0 ?
                    imgdec->params.maxHeight :
                    imgdec->height;
    /* Set displayWidth to 0 in order to use decoded image width */
    imgdec->dynParams.displayWidth = 0;

    /* Check for valid values (NOTE: minimum width and height are 64) */
    if (imgdec->params.maxWidth < 64) {
        GST_ERROR("The resolution width (%ld) is too small.  Must be at least 64\n", imgdec->params.maxWidth);
        return FALSE;
    }
    if (imgdec->params.maxHeight < 64) {
        GST_ERROR("The resolution height (%ld) is too small.  Must be at least 64\n", imgdec->params.maxHeight);
        return FALSE;
    }

    /* Make the color human readable */
    toColor = gst_tiimgdec_codec_color_space_to_str(imgdec->params.forceChromaFormat);

    GST_DEBUG("\nCodec Parameters:\n"
              "\tparams.maxWidth = %ld\n"
              "\tparams.maxHeight = %ld\n"
              "\tparams.forceChromaFormat = %ld (%s)\n"
              "\tparams.maxScans - %ld\n"
              "\tparams.dataEndianness = %ld\n",
              imgdec->params.maxWidth, imgdec->params.maxHeight,
              imgdec->params.forceChromaFormat, toColor,
              imgdec->params.maxScans, imgdec->params.dataEndianness);
    GST_LOG("Finish\n");
    return TRUE;
}

/*******************************************************************************
 * gst_tiimgdec_codec_color_space_to_dmai
 *      Convert the codec color space type to the corresponding color space
 *      used by DMAI.
*******************************************************************************/
static int gst_tiimgdec_codec_color_space_to_dmai(int cspace) {
    GST_LOG("Begin");
    switch (cspace) {
        case XDM_YUV_422ILE:
            GST_LOG("Finish");
            return ColorSpace_UYVY;
            break;
        case XDM_YUV_420P:
            GST_LOG("Finish");
            return ColorSpace_YUV420P;
            break;
        case XDM_YUV_422P:
            GST_LOG("Finish");
            return ColorSpace_YUV422P;
            break;
        default:
            GST_ERROR("Unsupported Color Space\n");
            GST_LOG("Finish");
            return -1;
    }
}

/******************************************************************************
 * gst_tiimgdec_init_image
 *     Initialize or re-initializes the image stream
 ******************************************************************************/
static gboolean gst_tiimgdec_init_image(GstTIImgdec *imgdec)
{
    Rendezvous_Attrs       rzvAttrs  = Rendezvous_Attrs_DEFAULT;
    struct sched_param     schedParam;
    pthread_attr_t         attr;
    Fifo_Attrs             fAttrs    = Fifo_Attrs_DEFAULT;

    GST_LOG("Begin\n");

    /* If image has already been initialized, shut down previous decoder */
    if (imgdec->hEngine) {
        if (!gst_tiimgdec_exit_image(imgdec)) {
            GST_ERROR("failed to shut down existing image decoder\n");
            return FALSE;
        }
    }

    /* Make sure we know what codec we're using */
    if (!imgdec->engineName) {
        GST_ERROR("engine name not specified\n");
        return FALSE;
    }

    if (!imgdec->codecName) {
        GST_ERROR("codec name not specified\n");
        return FALSE;
    }

    /* Set up the queue fifo */
    imgdec->hInFifo = Fifo_create(&fAttrs);

    /* Initialize thread status management */
    imgdec->threadStatus = 0UL;
    pthread_mutex_init(&imgdec->threadStatusMutex, NULL);

    /* Initialize rendezvous objects for making threads wait on conditions */
    imgdec->waitOnDecodeDrain  = Rendezvous_create(100, &rzvAttrs);
    imgdec->waitOnQueueThread  = Rendezvous_create(100, &rzvAttrs);
    imgdec->waitOnDecodeThread = Rendezvous_create(2, &rzvAttrs);
    imgdec->waitOnBufTab       = Rendezvous_create(100, &rzvAttrs);
    imgdec->drainingEOS        = FALSE;

    /* Initialize custom thread attributes */
    if (pthread_attr_init(&attr)) {
        GST_WARNING("failed to initialize thread attrs\n");
        gst_tiimgdec_exit_image(imgdec);
        return FALSE;
    }

    /* Force the thread to use the system scope */
    if (pthread_attr_setscope(&attr, PTHREAD_SCOPE_SYSTEM)) {
        GST_WARNING("failed to set scope attribute\n");
        gst_tiimgdec_exit_image(imgdec);
        return FALSE;
    }

    /* Force the thread to use custom scheduling attributes */
    if (pthread_attr_setinheritsched(&attr, PTHREAD_EXPLICIT_SCHED)) {
        GST_WARNING("failed to set schedule inheritance attribute\n");
        gst_tiimgdec_exit_image(imgdec);
        return FALSE;
    }

    /* Set the thread to be fifo real time scheduled */
    if (pthread_attr_setschedpolicy(&attr, SCHED_FIFO)) {
        GST_WARNING("failed to set FIFO scheduling policy\n");
        gst_tiimgdec_exit_image(imgdec);
        return FALSE;
    }

    /* Set the display thread priority */
    schedParam.sched_priority = GstTIVideoThreadPriority;
    if (pthread_attr_setschedparam(&attr, &schedParam)) {
        GST_WARNING("failed to set scheduler parameters\n");
        return FALSE;
    }

    /* Create decoder thread */
    if (pthread_create(&imgdec->decodeThread, &attr,
            gst_tiimgdec_decode_thread, (void*)imgdec)) {
        GST_ERROR("failed to create decode thread\n");
        gst_tiimgdec_exit_image(imgdec);
        return FALSE;
    }
    gst_tithread_set_status(imgdec, TIThread_DECODE_CREATED);

    /* Wait for decoder thread to finish initilization before creating queue
     * thread.
     */
    Rendezvous_meet(imgdec->waitOnDecodeThread);

    /* Make sure circular buffer and display buffer handles are created by
     * decoder thread.
     */
    if (imgdec->circBuf == NULL || imgdec->hOutBufTab == NULL) {
        GST_ERROR("decode thread failed to create circbuf or display buffer"
                  " handles\n");
        return FALSE;
    }

    /* Create queue thread */
    if (pthread_create(&imgdec->queueThread, NULL,
            gst_tiimgdec_queue_thread, (void*)imgdec)) {
        GST_ERROR("failed to create queue thread\n");
        gst_tiimgdec_exit_image(imgdec);
        return FALSE;
    }
    gst_tithread_set_status(imgdec, TIThread_QUEUE_CREATED);


    GST_LOG("Finish\n");
    return TRUE;
}


/******************************************************************************
 * gst_tiimgdec_exit_image
 *    Shut down any running image decoder, and reset the element state.
 ******************************************************************************/
static gboolean gst_tiimgdec_exit_image(GstTIImgdec *imgdec)
{
    void*    thread_ret;
    gboolean checkResult;

    GST_LOG("Begin\n");

    /* Drain the pipeline if it hasn't already been drained */
    if (!imgdec->drainingEOS) {
       gst_tiimgdec_drain_pipeline(imgdec);
     }

    /* Shut down the decode thread */
    if (gst_tithread_check_status(
            imgdec, TIThread_DECODE_CREATED, checkResult)) {
        GST_LOG("shutting down decode thread\n");

        if (pthread_join(imgdec->decodeThread, &thread_ret) == 0) {
            if (thread_ret == GstTIThreadFailure) {
                GST_DEBUG("decode thread exited with an error condition\n");
            }
        }
    }

    /* Shut down the queue thread */
    if (gst_tithread_check_status(
            imgdec, TIThread_QUEUE_CREATED, checkResult)) {
        GST_LOG("shutting down queue thread\n");

        /* Unstop the queue thread if needed, and wait for it to finish */
        /* Push the gst_ti_flush_fifo buffer to let the queue thread know
         * when the Fifo has finished draining.  If the Fifo is currently
         * empty when we get to this point, then pushing this buffer will
         * also unblock the encode/decode thread if it is currently blocked
         * on a Fifo_get().  Our first thought was to use DMAI's Fifo_flush()
         * routine here, but this method assumes the Fifo to be empty and
         * will leak any buffer still in the Fifo.
         */
        if (Fifo_put(imgdec->hInFifo,&gst_ti_flush_fifo) < 0) {
            GST_ERROR("Could not put flush value to Fifo\n");
        }

        if (pthread_join(imgdec->queueThread, &thread_ret) == 0) {
            if (thread_ret == GstTIThreadFailure) {
                GST_DEBUG("queue thread exited with an error condition\n");
            }
        }
    }

    if (imgdec->hInFifo) {
        Fifo_delete(imgdec->hInFifo);
        imgdec->hInFifo = NULL;
    }

    if (imgdec->waitOnQueueThread) {
        Rendezvous_delete(imgdec->waitOnQueueThread);
        imgdec->waitOnQueueThread = NULL;
    }

    if (imgdec->waitOnDecodeDrain) {
        Rendezvous_delete(imgdec->waitOnDecodeDrain);
        imgdec->waitOnDecodeDrain = NULL;
    }

    if (imgdec->waitOnDecodeThread) {
        Rendezvous_delete(imgdec->waitOnDecodeThread);
        imgdec->waitOnDecodeThread = NULL;
    }

    if (imgdec->waitOnBufTab) {
        Rendezvous_delete(imgdec->waitOnBufTab);
        imgdec->waitOnBufTab = NULL;
    }

    /* Shut down thread status management */
    imgdec->threadStatus = 0UL;
    pthread_mutex_destroy(&imgdec->threadStatusMutex);

    /* Shut down remaining items */
    if (imgdec->circBuf) {
        GST_LOG("freeing cicrular input buffer\n");
        gst_ticircbuffer_unref(imgdec->circBuf);
        imgdec->circBuf      = NULL;
        imgdec->framerateNum = 0;
        imgdec->framerateDen = 0;
    }

    if (imgdec->hOutBufTab) {
        GST_LOG("freeing output buffers\n");
        BufTab_delete(imgdec->hOutBufTab);
        imgdec->hOutBufTab = NULL;
    }

    GST_LOG("Finish\n");
    return TRUE;
}


/******************************************************************************
 * gst_tiimgdec_change_state
 *     Manage state changes for the image stream.  The gStreamer documentation
 *     states that state changes must be handled in this manner:
 *        1) Handle ramp-up states
 *        2) Pass state change to base class
 *        3) Handle ramp-down states
 ******************************************************************************/
static GstStateChangeReturn gst_tiimgdec_change_state(GstElement *element,
                                GstStateChange transition)
{
    GstStateChangeReturn  ret    = GST_STATE_CHANGE_SUCCESS;
    GstTIImgdec          *imgdec = GST_TIIMGDEC(element);

    GST_LOG("Begin change_state (%d)\n", transition);

    /* Handle ramp-up state changes */
    switch (transition) {
        case GST_STATE_CHANGE_NULL_TO_READY:
            break;
        default:
            break;
    }

    /* Pass state changes to base class */
    ret = GST_ELEMENT_CLASS(parent_class)->change_state(element, transition);
    if (ret == GST_STATE_CHANGE_FAILURE)
        return ret;

    /* Handle ramp-down state changes */
    switch (transition) {
        case GST_STATE_CHANGE_READY_TO_NULL:
            GST_LOG("State changed from READY to NULL.  Shutting down any"
                    "running image decoders\n");
            /* Shut down any running image decoder */
            if (!gst_tiimgdec_exit_image(imgdec)) {
                return GST_STATE_CHANGE_FAILURE;
            }
            break;

        default:
            break;
    }

    GST_LOG("Finish change_state\n");
    return ret;
}

/******************************************************************************
 * gst_tiimgdec_codec_stop
 *     Stop codec engine
 *****************************************************************************/
static gboolean gst_tiimgdec_codec_stop (GstTIImgdec  *imgdec)
{
    if (imgdec->hIe) {
        GST_LOG("closing image decoder\n");
        Idec_delete(imgdec->hIe);
        imgdec->hIe = NULL;
    }

    if (imgdec->hEngine) {
        GST_LOG("closing codec engine\n");
        Engine_close(imgdec->hEngine);
        imgdec->hEngine = NULL;
    }

    return TRUE;
}


/******************************************************************************
 * gst_tiimgdec_codec_start
 *     Initialize codec engine
 *****************************************************************************/
static gboolean gst_tiimgdec_codec_start (GstTIImgdec  *imgdec)
{
    BufferGfx_Attrs        gfxAttrs  = BufferGfx_Attrs_DEFAULT;

    /* Open the codec engine */
    GST_LOG("opening codec engine \"%s\"\n", imgdec->engineName);
    imgdec->hEngine = Engine_open((Char *) imgdec->engineName, NULL, NULL);

    if (imgdec->hEngine == NULL) {
        GST_ERROR("failed to open codec engine \"%s\"\n", imgdec->engineName);
        return FALSE;
    }
    GST_LOG("opened codec engine \"%s\" successfully\n", imgdec->engineName);

    if (!gst_tiimgdec_set_codec_attrs(imgdec)) {
        GST_ERROR("Error while trying to set the codec attrs\n");
        return FALSE;
    }

    GST_LOG("opening image decoder \"%s\"\n", imgdec->codecName);
    imgdec->hIe = Idec_create(imgdec->hEngine, (Char*)imgdec->codecName,
                      &imgdec->params, &imgdec->dynParams);

    if (imgdec->hIe == NULL) {
        GST_ERROR("failed to create image decoder: %s\n", imgdec->codecName);
        GST_DEBUG("Verify that the values being used for input and output ColorSpace are supported by your coded.\n");
        GST_LOG("closing codec engine\n");
        return FALSE;
    }

    /* Create a circular input buffer */
    imgdec->circBuf = gst_ticircbuffer_new(
                           Idec_getInBufSize(imgdec->hIe), 3, FALSE);

    if (imgdec->circBuf == NULL) {
        GST_ERROR("failed to create circular input buffer\n");
        return FALSE;
    }

    /* Display buffer contents if displayBuffer=TRUE was specified */
    gst_ticircbuffer_set_display(imgdec->circBuf, imgdec->displayBuffer);

    /* Define the number of display buffers to allocate.  This number must be
     * at least 1, but should be more if codecs don't return a display buffer
     * after every process call.  If this has not been set via set_property(),
     * default to the value set above based on device type.
     */
    if (imgdec->numOutputBufs == 0) {
        imgdec->numOutputBufs = 1;
    }

    /* Create codec output buffers */
    GST_LOG("creating output buffer table\n");
    gfxAttrs.colorSpace     = gst_tiimgdec_codec_color_space_to_dmai(imgdec->params.forceChromaFormat);
    gfxAttrs.dim.width      = imgdec->params.maxWidth;
    gfxAttrs.dim.height     = imgdec->params.maxHeight;
    gfxAttrs.dim.lineLength = BufferGfx_calcLineLength(
                                  gfxAttrs.dim.width, gfxAttrs.colorSpace);

    gfxAttrs.bAttrs.memParams.align = 128;
    /* Both the codec and the GStreamer pipeline can own a buffer */
    gfxAttrs.bAttrs.useMask = gst_tidmaibuffertransport_GST_FREE |
                              gst_tiimgdec_CODEC_FREE;

    imgdec->hOutBufTab =
        BufTab_create(imgdec->numOutputBufs, Idec_getOutBufSize(imgdec->hIe),
            BufferGfx_getBufferAttrs(&gfxAttrs));

    if (imgdec->hOutBufTab == NULL) {
        GST_ERROR("failed to create output buffers\n");
        return FALSE;
    }

    return TRUE;
}

/******************************************************************************
 * gst_tiimgdec_decode_thread
 *     Call the image codec to process a full input buffer
 ******************************************************************************/
static void* gst_tiimgdec_decode_thread(void *arg)
{
    GstTIImgdec           *imgdec        = GST_TIIMGDEC(gst_object_ref(arg));
    GstBuffer              *encDataWindow  = NULL;
    gboolean               codecFlushed    = FALSE;
    void                   *threadRet      = GstTIThreadSuccess;
    BufferGfx_Attrs        gfxAttrs        = BufferGfx_Attrs_DEFAULT;
    Buffer_Handle          hDstBuf;
    Int32                  encDataConsumed;
    GstClockTime           encDataTime;
    GstClockTime           frameDuration;
    Buffer_Handle          hEncDataWindow;
    BufferGfx_Dimensions   dim;
    GstBuffer              *outBuf;
    Int                    ret;


    GST_LOG("Begin\n");
    /* Calculate the duration of a single frame in this stream */
    frameDuration = gst_tiimgdec_frame_duration(imgdec);

    /* Initialize codec engine */
    ret = gst_tiimgdec_codec_start(imgdec);

    /* Notify main thread if it is waiting to create queue thread */
    Rendezvous_meet(imgdec->waitOnDecodeThread);

    if (ret == FALSE) {
        GST_ERROR("failed to start codec\n");
        goto thread_exit;
    }

    /* Main thread loop */
    while (TRUE) {

        /* Obtain an encoded data frame */
        encDataWindow  = gst_ticircbuffer_get_data(imgdec->circBuf);
        encDataTime    = GST_BUFFER_TIMESTAMP(encDataWindow);
        hEncDataWindow = GST_TIDMAIBUFFERTRANSPORT_DMAIBUF(encDataWindow);

        /* If we received a data frame of zero size, there is no more data to
         * process -- exit the thread.  If we weren't told that we are
         * draining the pipeline, something is not right, so exit with an
         * error.
         */
        if (GST_BUFFER_SIZE(encDataWindow) == 0) {
            GST_LOG("no image data remains\n");
            if (!imgdec->drainingEOS) {
                goto thread_failure;
            }

            goto thread_exit;
        }

        /* Obtain a free output buffer for the decoded data */
        /* If we are not able to find free buffer from BufTab then decoder 
         * thread will be blocked on waitOnBufTab rendezvous. And this will be 
         * woke-up by dmaitransportbuffer finalize method.
         */
        hDstBuf = BufTab_getFreeBuf(imgdec->hOutBufTab);
        if (hDstBuf == NULL) {
            Rendezvous_meet(imgdec->waitOnBufTab);
            hDstBuf = BufTab_getFreeBuf(imgdec->hOutBufTab);

            if (hDstBuf == NULL) {
                GST_ERROR("failed to get a free contiguous buffer from"
                            " BufTab\n");
                goto thread_failure;
            }
        }

        /* Reset waitOnBufTab rendezvous handle to its orignal state */
        Rendezvous_reset(imgdec->waitOnBufTab);

        /* Make sure the whole buffer is used for output */
        BufferGfx_resetDimensions(hDstBuf);

        /* Create a BufferGfx object that will point to a reference buffer from
         * The circular buffer.  This is needed for the decoder which requires
         * that the input buffer be a BufferGfx object.
         */
        BufferGfx_getBufferAttrs(&gfxAttrs)->reference = TRUE;
        imgdec->hInBuf = Buffer_create(Buffer_getSize(hEncDataWindow),
                                BufferGfx_getBufferAttrs(&gfxAttrs));
        Buffer_setUserPtr(imgdec->hInBuf, Buffer_getUserPtr(hEncDataWindow));
        Buffer_setNumBytesUsed(imgdec->hInBuf, 
                               Buffer_getSize(imgdec->hInBuf));

        /* Set the dimensions of the buffer to the resolution */
        BufferGfx_getDimensions(hDstBuf, &dim);
        dim.width = imgdec->params.maxWidth;
        dim.height = imgdec->params.maxHeight;
        BufferGfx_setColorSpace(imgdec->hInBuf,
                     ColorSpace_UYVY); 
        dim.lineLength = BufferGfx_calcLineLength(imgdec->params.maxWidth,
                                  gfxAttrs.colorSpace);

        BufferGfx_setDimensions(hDstBuf, &dim);
        Buffer_setNumBytesUsed(hDstBuf, Buffer_getSize(hDstBuf));

        /* Invoke the image decoder */
        GST_LOG("invoking the image decoder\n");
        ret             = Idec_process(imgdec->hIe, imgdec->hInBuf, hDstBuf);
        encDataConsumed = (codecFlushed) ? 0 :
                          Buffer_getNumBytesUsed(hEncDataWindow);

        /* Delete the temporary Graphics buffer used for the decode process */
        Buffer_delete(imgdec->hInBuf);

        if (ret < 0) {
            GST_ERROR("failed to decode image buffer\n");
            goto thread_failure;
        }

        /* If no data was used we must have some kind of decode error */
        if (ret == Dmai_EBITERROR && encDataConsumed == 0 && !codecFlushed) {
            GST_ERROR("fatal bit error\n");
            goto thread_failure;
        }

        if (ret > 0) {
            GST_LOG("Idec_process returned success code %d\n", ret); 
        }

        /* Release the referdece buffer, and tell the circular buffer how much
         * data was consumed.
         */
        ret = gst_ticircbuffer_data_consumed(imgdec->circBuf, encDataWindow,
                  encDataConsumed);
        encDataWindow = NULL;

        if (!ret) {
            goto thread_failure;
        }


        /* Set the source pad capabilities based on the decoded frame
         * properties.
         */
        gst_tiimgdec_set_source_caps(imgdec, hDstBuf);

        /* Create a DMAI transport buffer object to carry a DMAI buffer to
         * the source pad.  The transport buffer knows how to release the
         * buffer for re-use in this element when the source pad calls
         * gst_buffer_unref().
         */
        outBuf = gst_tidmaibuffertransport_new(hDstBuf, imgdec->waitOnBufTab);
        gst_buffer_set_data(outBuf, GST_BUFFER_DATA(outBuf),
             gst_ti_calculate_display_bufSize(hDstBuf));
        gst_buffer_set_caps(outBuf, GST_PAD_CAPS(imgdec->srcpad));

        /* If we have a valid time stamp, set it on the buffer */
        if (imgdec->genTimeStamps &&
            GST_CLOCK_TIME_IS_VALID(encDataTime)) {
            GST_LOG("image timestamp value: %llu\n", encDataTime);
            GST_BUFFER_TIMESTAMP(outBuf) = encDataTime;
            GST_BUFFER_DURATION(outBuf)  = frameDuration;
        }
        else {
            GST_BUFFER_TIMESTAMP(outBuf) = GST_CLOCK_TIME_NONE;
        }

        /* Tell circular buffer how much time we consumed */
        gst_ticircbuffer_time_consumed(imgdec->circBuf, frameDuration);

        /* Push the transport buffer to the source pad */
        GST_LOG("pushing display buffer to source pad\n");

        if (gst_pad_push(imgdec->srcpad, outBuf) != GST_FLOW_OK) {
            GST_DEBUG("push to source pad failed\n");
            goto thread_failure;
        }

        /* Release buffers no longer in use by the codec */
        Buffer_freeUseMask(hDstBuf, gst_tiimgdec_CODEC_FREE);
    }

thread_failure:

    /* If decDataWindow is non-NULL, something bad happened before we had a
     * chance to release it.  Release it now so we don't block the pipeline.
     * We release it by telling the circular buffer that we're done with it and
     * consumed no data.
     */
    if (encDataWindow) {
        gst_ticircbuffer_data_consumed(imgdec->circBuf, encDataWindow, 0);
    }

    gst_tithread_set_status(imgdec, TIThread_DECODE_ABORTED);
    threadRet = GstTIThreadFailure;
    gst_ticircbuffer_consumer_aborted(imgdec->circBuf);
    Rendezvous_force(imgdec->waitOnQueueThread);

thread_exit:
 
    /* Stop codec engine */
    if (gst_tiimgdec_codec_stop(imgdec) < 0) {
        GST_ERROR("failed to stop codec\n");
    }

    imgdec->decodeDrained = TRUE;
    Rendezvous_force(imgdec->waitOnDecodeDrain);

    gst_object_unref(imgdec);

    GST_LOG("Finish image decode_thread (%d)\n", (int)threadRet);
    return threadRet;
}


/******************************************************************************
 * gst_tiimgdec_queue_thread 
 *     Add an input buffer to the circular buffer            
 ******************************************************************************/
static void* gst_tiimgdec_queue_thread(void *arg)
{
    GstTIImgdec* imgdec    = GST_TIIMGDEC(gst_object_ref(arg));
    void*        threadRet = GstTIThreadSuccess;
    GstBuffer*   decData;
    Int          fifoRet;

    GST_LOG("Begin\n");
    while (TRUE) {

        /* Get the next input buffer (or block until one is ready) */
        fifoRet = Fifo_get(imgdec->hInFifo, &decData);

        if (fifoRet < 0) {
            GST_ERROR("Failed to get buffer from input fifo\n");
            goto thread_failure;
        }

        if (decData == (GstBuffer *)(&gst_ti_flush_fifo)) {
            GST_DEBUG("Processed last input buffer from Fifo; exiting.\n");
            goto thread_exit;
        }

/* This code is if'ed out for now until more work has been done for state
 * transitions.  For now we do not want to print this message repeatedly
 * which will happen when flushing the fifo when the decode thread has
 * exited.
 */
        /* Send the buffer to the circular buffer */
        if (!gst_ticircbuffer_queue_data(imgdec->circBuf, decData)) {
#if 0
            GST_ERROR("queue thread could not queue data\n");
            GST_ERROR("queue thread encData size = %d\n", GST_BUFFER_SIZE(encData));
            gst_buffer_unref(encData);
            goto thread_failure;
#else
            ; /* Do nothing */
#endif
        }

        /* Release the buffer we received from the sink pad */
        gst_buffer_unref(decData);

        /* If we've reached the EOS, start draining the circular buffer when
         * there are no more buffers in the FIFO.
         */
        if (imgdec->drainingEOS && 
            Fifo_getNumEntries(imgdec->hInFifo) == 0) {
            gst_ticircbuffer_drain(imgdec->circBuf, TRUE);
        }

        /* Unblock any pending puts to our Fifo if we have reached our
         * minimum threshold.
         */
        gst_tiimgdec_broadcast_queue_thread(imgdec);
    }

thread_failure:
    gst_tithread_set_status(imgdec, TIThread_QUEUE_ABORTED);
    threadRet = GstTIThreadFailure;

thread_exit:
    gst_object_unref(imgdec);
    GST_LOG("Finish\n");
    return threadRet;
}


/******************************************************************************
 * gst_tiimgdec_wait_on_queue_thread
 *    Wait for the queue thread to consume buffers from the fifo until
 *    there are only "waitQueueSize" items remaining.
 ******************************************************************************/
static void gst_tiimgdec_wait_on_queue_thread(GstTIImgdec *imgdec,
                Int32 waitQueueSize)
{
    GST_LOG("Begin\n");
    imgdec->waitQueueSize = waitQueueSize;
    Rendezvous_meet(imgdec->waitOnQueueThread);
    GST_LOG("Finish\n");
}


/******************************************************************************
 * gst_tiimgdec_broadcast_queue_thread
 *    Broadcast when queue thread has processed enough buffers from the
 *    fifo to unblock anyone waiting to queue some more.
 ******************************************************************************/
static void gst_tiimgdec_broadcast_queue_thread(GstTIImgdec *imgdec)
{
    GST_LOG("Begin\n");
    if (imgdec->waitQueueSize < Fifo_getNumEntries(imgdec->hInFifo)) {
          return;
    } 
    Rendezvous_force(imgdec->waitOnQueueThread);
    GST_LOG("Finish\n");
}


/******************************************************************************
 * gst_tiimgdec_drain_pipeline
 *    Push any remaining input buffers through the queue and decode threads
 ******************************************************************************/
static void gst_tiimgdec_drain_pipeline(GstTIImgdec *imgdec)
{
    gboolean checkResult;

    GST_LOG("Begin\n");
    imgdec->drainingEOS = TRUE;

    /* If the processing threads haven't been created, there is nothing to
     * drain.
     */
    if (!gst_tithread_check_status(
             imgdec, TIThread_DECODE_CREATED, checkResult)) {
        return;
    }
    if (!gst_tithread_check_status(
             imgdec, TIThread_QUEUE_CREATED, checkResult)) {
        return;
    }

    /* If the queue fifo still has entries in it, it will drain the
     * circular buffer once all input buffers have been added to the
     * circular buffer.  If the fifo is already empty, we must drain
     * the circular buffer here.
     */
    if (Fifo_getNumEntries(imgdec->hInFifo) == 0) {
        gst_ticircbuffer_drain(imgdec->circBuf, TRUE);
    }
    else {
        Rendezvous_force(imgdec->waitOnQueueThread);
    }

    /* Wait for the decoder to drain */
    if (!imgdec->decodeDrained) {
        Rendezvous_meet(imgdec->waitOnDecodeDrain);
    }
    imgdec->decodeDrained = FALSE;

    GST_LOG("Finish\n");
}


/******************************************************************************
 * gst_tiimgdec_frame_duration
 *    Return the duration of a single frame in nanoseconds.
 ******************************************************************************/
static GstClockTime gst_tiimgdec_frame_duration(GstTIImgdec *imgdec)
{
    GST_LOG("Begin\n");
    /* Default to 29.97 if the frame rate was not specified */
    if (imgdec->framerateNum == 0 && imgdec->framerateDen == 0) {
        GST_DEBUG("framerate not specified; using 29.97fps");
        imgdec->framerateNum = 30000;
        imgdec->framerateDen = 1001;
    }

    GST_LOG("Finish\n");
    return (GstClockTime)
        ((1 / ((gdouble)imgdec->framerateNum/(gdouble)imgdec->framerateDen))
         * GST_SECOND);
}


/******************************************************************************
 * Custom ViM Settings for editing this file
 ******************************************************************************/
#if 0
 Tabs (use 4 spaces for indentation)
 vim:set tabstop=4:      /* Use 4 spaces for tabs          */
 vim:set shiftwidth=4:   /* Use 4 spaces for >> operations */
 vim:set expandtab:      /* Expand tabs into white spaces  */
#endif
